### ISSUE TITLE
Add another comparison?

### ISSUE THREAD

**Issue by xueshanf** [tallpauley/vault-unsealer#7]
[hookpick](https://github.com/jaxxstorm/hookpick). I am evaluating unseal tools but do not have enough run-time experience to compare. Thanks!

**Comment by tallpauley** [comment]
Thanks Xueshan. I'd be glad to add it. Right now the comparison is solely
on how the unseal keys are stored (hookpick looks to use config files from
a glance), but hookpick also allows multiple vault targets, so I should add
a comparison about # of targets. For vault unsealer, it would be convenient
if a single instance could unseal all the vault instances in a cluster.

On Oct 28, 2017 1:19 PM, "Xueshan Feng" <notifications@github.com> wrote:

hookpick <https://github.com/jaxxstorm/hookpick>. I am evaluating unseal
tools but do not have enough run-time experience to compare. Thanks!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/tallpauley/vault-unsealer/issues/7>, or mute the thread

**Comment by tallpauley** [comment]
@xueshanf Added hookpick to the comparison. While it can decrypt PGP-encrypted unseal keys w/ GPG, I don't like that model because it means private PGP keys have to go on your server, manual entry of PGP passcode on server, and a GPG session on the server which allows reading the unseal keys.

**Comment by xueshanf** [comment]
@tallpauley make sense. Thank you!
